title: Finding Moments in Video Collections Using Natural Language
description: Victor Escorcia, Mattia Soldan, Josef Sivic, Bernard Ghanem, Bryan Russell
show_downloads: False
google_analytics:
theme: jekyll-theme-cayman
